name: "Build things..."

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gather files changed
        uses: trilom/file-changes-action@a6ca26c14274c33b15e6499323aac178af06ad4b
        with:
          fileOutput: " "
          output: " "

      - name: Show files changed
        run: cat $HOME/files.txt

      - name: Show which dirs changed.
        run: awk '{ print $1}' FS=/ $HOME/files.txt

      - name: build server
        run: |
          awk '{ print $1 }' FS=/ $HOME/files.txt | grep server;
          # if [ $? -eq 0 ]; then 
          #   cd server && ls 
          # fi
