name: "Build things..."

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  predeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gather files changed
        uses: trilom/file-changes-action@a6ca26c14274c33b15e6499323aac178af06ad4b
        with:
          fileOutput: " "
          output: " "

      - name: Show files changed
        run: cat $HOME/files.txt

      - name: determine if to build server
        id: predeploy-server
        run: |
          res=$(sed -i 's/\s/\n/g' $HOME/files.txt && awk '{ print $1 }' FS=/ $HOME/files.txt | grep server | wc -l)
          if [ $res -eq 1 ]; then 
            cd server && ls 
            echo "server=true" >> $GITHUB_OUTPUT
          else
            echo "server=false" >> $GITHUB_OUTPUT
            echo "no deploy this time"
          fi

      - name: determine if to build cli
        id: predeploy-cli
        run: |
          res=$(sed -i 's/\s/\n/g' $HOME/files.txt && awk '{ print $1 }' FS=/ $HOME/files.txt | grep cli | wc -l)
          if [ $res -eq 1 ]; then 
            cd cli && ls 
            echo "cli=true" >> $GITHUB_OUTPUT
          else
            echo "cli=false" >> $GITHUB_OUTPUT
            echo "no deploy this time"
          fi

      - name: Set cli deploy data
        uses: edumserrano/share-jobs-data@v1
        with:
          command: set-data
          data: |
            cli: ${{ steps.predeploy-cli.outputs.cli }}
            server: ${{ steps.predeploy-server.outputs.server }}

  deploy_cli:
    needs: predeploy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            label: windows
            archive: zip
          - target: x86_64-unknown-linux-musl
            label: linux
            archive: tar.gz
          #- target: x86_64-apple-darwin
          #  label: macos
          #  archive: zip
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read data
        id: read-data # must have an id so that you can access the output from this step which contains the shared data
        uses: edumserrano/share-jobs-data@v1
        with:
          command: read-data-current-workflow

      - name: Compile and release
        if: ${{ contains(steps.read-data.outputs.cli, 'true') }}
        uses: rust-build/rust-build.action@v1.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          SRC_DIR: cli/zeus
          ARCHIVE_NAME: ${{ matrix.label }}.${{ matrix.archive }}
          MINIFY: true
          TOOLCHAIN_VERSION: nightly-x86_64-unknown-linux-musl
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}

      - name: Compile and release
        if: ${{ contains(steps.read-data.outputs.cli, 'true') }}
        uses: rust-build/rust-build.action@v1.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          SRC_DIR: cli/zeusd
          ARCHIVE_NAME: ${{ matrix.label }}.${{ matrix.archive }}
          MINIFY: true
          TOOLCHAIN_VERSION: nightly-x86_64-unknown-linux-musl
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}

      - name: Show files changed
        run: |
          ls -a cli/
          ls -a cli/zeus/target/${{ matrix.target }}/release
          ls -a cli/zeusd/target/${{ matrix.target }}/release

      - uses: jakejarvis/s3-sync-action@master
        if: ${{ contains(steps.read-data.outputs.cli, 'true') }}
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: cli/zeus/target/${{ matrix.target }}/release/zeus.*

      - uses: jakejarvis/s3-sync-action@master
        if: ${{ contains(steps.read-data.outputs.cli, 'true') }}
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: cli/zeusd/target/${{ matrix.target }}/release/zeusd.*

  deploy_server:
    needs: predeploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read data
        id: read-data # must have an id so that you can access the output from this step which contains the shared data
        uses: edumserrano/share-jobs-data@v1
        with:
          command: read-data-current-workflow

      - name: ish..
        run: echo ${{ steps.read-data.outputs.server }}

      - name: Configure AWS credentials
        if: ${{ contains(steps.read-data.outputs.server, 'true') }}
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: samplerolesession
          aws-region: us-east-1

      - name: Login to Amazon ECR
        if: ${{ contains(steps.read-data.outputs.server, 'true') }}
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: build and deploy server
        if: ${{ contains(steps.read-data.outputs.server, 'true') }}
        id: predeploy
        run: |
          cd server && ls 
          docker build -t zeus .
          docker tag zeus ${{ secrets.DOCKER_REPOSITORY }}:latest
          docker push ${{ secrets.DOCKER_REPOSITORY }}:latest

      - name: Deploy to Staging server
        if: ${{ contains(steps.read-data.outputs.server, 'true') }}
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "deployments/*"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          SCRIPT_BEFORE: |
            ls -al
          SCRIPT_AFTER: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.DOCKER_REPOSITORY }}
            cd zeus
            docker compose pull
            docker compose up -d
