name: "Build things..."

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  predeploy:
    runs-on: ubuntu-latest
    outputs:
      should_deploy_cli: ${{ steps.predeploy-cli.outputs.cli }}
      should_deploy_server: ${{ steps.predeploy-server.outputs.server }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gather files changed
        uses: trilom/file-changes-action@a6ca26c14274c33b15e6499323aac178af06ad4b
        with:
          fileOutput: " "
          output: " "

      - name: Show files changed
        run: cat $HOME/files.txt

      - name: determine if to build server
        id: predeploy-server
        run: |
          res=$(sed -i 's/\s/\n/g' $HOME/files.txt && awk '{ print $1 }' FS=/ $HOME/files.txt | grep server | wc -l)
          if [ $res -gt 0 ]; then 
            cd server && ls 
            echo "server=true" >> $GITHUB_OUTPUT
          else
            echo "no deploy this time"
            echo "server=false" >> $GITHUB_OUTPUT
          fi

      - name: determine if to build cli
        id: predeploy-cli
        run: |
          res=$(sed -i 's/\s/\n/g' $HOME/files.txt && awk '{ print $1 }' FS=/ $HOME/files.txt | grep cli | wc -l)
          if [ $res -gt 0 ]; then 
            cd cli && ls 
            echo "cli=true" >> $GITHUB_OUTPUT
          else
            echo "no deploy this time"
            echo "cli=false" >> $GITHUB_OUTPUT
          fi

      - name: Set deploy determination data
        uses: edumserrano/share-jobs-data@v1
        with:
          command: set-data
          data: |
            cli: ${{ steps.predeploy-cli.outputs.cli }}
            server: ${{ steps.predeploy-server.outputs.server }}

  deploy_cli_macos:
    needs: predeploy
    if: ${{ contains(needs.predeploy.outputs.should_deploy_cli, 'true') }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-apple-darwin
            label: macos
            archive: zip
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: hecrj/setup-rust-action@v2
        with:
          rust-version: nightly

      - name: Compile zeus
        run: |
          cd cli
          cargo build -p zeus --release --target x86_64-apple-darwin 
          ls

      - name: Compile zeusd
        run: |
          cd cli
          cargo build -p zeusd --release --target x86_64-apple-darwin 
          ls

      - name: zip zeus.
        run: |
          mkdir -p cli/out
          cd cli/target/release
          ls
          zip ../cli/out/zeus.${{ matrix.label }}.zip zeus*

      - uses: hkusu/s3-upload-action@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-bucket: ${{ secrets.AWS_S3_BUCKET }}
          public: true
          destination-dir: /
          aws-region: us-east-1
          file-path: cli/out/zeus.${{ matrix.label }}.zip

  deploy_cli:
    needs: predeploy
    runs-on: ubuntu-latest
    if: ${{ contains(needs.predeploy.outputs.should_deploy_cli, 'true') }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            label: windows
            archive: zip
          - target: x86_64-unknown-linux-musl
            label: linux
            archive: tar.gz
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile zeus
        id: compile-zeus
        uses: rust-build/rust-build.action@v1.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          SRC_DIR: cli/zeus
          ARCHIVE_NAME: zeus.${{ matrix.label }}
          MINIFY: true
          TOOLCHAIN_VERSION: nightly-x86_64-unknown-linux-musl
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          UPLOAD_MODE: none

      - name: Compile zeusd
        id: compile-zeusd
        uses: rust-build/rust-build.action@v1.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          SRC_DIR: cli/zeusd
          ARCHIVE_NAME: zeusd.${{ matrix.label }}
          MINIFY: true
          TOOLCHAIN_VERSION: nightly-x86_64-unknown-linux-musl
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          UPLOAD_MODE: none

      - name: zip zeus.
        run: |
          mkdir -p cli/out
          cd output
          zip ../cli/out/zeus.${{ matrix.label }}.zip zeus*

      - uses: hkusu/s3-upload-action@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-bucket: ${{ secrets.AWS_S3_BUCKET }}
          public: true
          destination-dir: /
          aws-region: us-east-1
          file-path: cli/out/zeus.${{ matrix.label }}.zip

  deploy_server:
    needs: predeploy
    if: ${{ contains(needs.predeploy.outputs.should_deploy_server, 'true') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: samplerolesession
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: build and deploy server
        id: predeploy
        run: |
          cd server && ls 
          docker build -t zeus .
          docker tag zeus ${{ secrets.DOCKER_REPOSITORY }}:latest
          docker push ${{ secrets.DOCKER_REPOSITORY }}:latest

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "deployments/*"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          SCRIPT_BEFORE: |
            ls -al
          SCRIPT_AFTER: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.DOCKER_REPOSITORY }}
            cd zeus
            docker compose pull
            docker compose up -d
