name: "Build things..."

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gather files changed
        uses: trilom/file-changes-action@a6ca26c14274c33b15e6499323aac178af06ad4b
        with:
          fileOutput: " "
          output: " "

      - name: Show files changed
        run: cat $HOME/files.txt

      - name: Show which dirs changed.
        run: awk '{ print $1}' FS=/ $HOME/files.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          aws-region: aws-region-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: build and deploy server
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: zeus
          IMAGE_TAG: latest
        run: |
          res=$(awk '{ print $1 }' FS=/ $HOME/files.txt | grep server | wc -l)
          if [ $res -eq 1 ]; then 
            cd server && ls 
            docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
            docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          else
            echo "no deploy this time"
          fi

      - name: build and deploy cli program
        run: |
          res=$(awk '{ print $1 }' FS=/ $HOME/files.txt | grep cli | wc -l)
          if [ $res -eq 1 ]; then 
            cd server && ls 
          else
            echo "no deploy this time"
          fi
          
